import { createHash, randomBytes } from "node:crypto";

export function hashApiKey(key: string): string {
  return createHash("sha256")
    .update(key, "utf8")
    .digest("hex");
}

export function generateApiKeySecret(): {
  key: string;
  keyHash: string;
  keyPrefix: string;
} {
  const key = `tsk_${randomBytes(32).toString("base64url")}`;

  return {
    key,
    keyHash: hashApiKey(key),
    keyPrefix: key.slice(0, 12),
  };
}

export function hasValidApiKeyFormat(value: string): boolean {
  if (!/^tsk_[A-Za-z0-9_-]{43}$/.test(value)) {
    return false;
  }

  const encoded = value.slice(4);
  const bytes = Buffer.from(encoded, "base64url");

  // Require the canonical encoding generated by our application.
  return bytes.length === 32 &&
    bytes.toString("base64url") === encoded;
}
